[package]
name = "interop_csharp_ts"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3.77"
web-sys = { version = "0.3", features = ["XmlHttpRequest", "console"] }

[lib]
crate-type = ["cdylib"]
